@IgniteDistribCaching_HostAddress = http://localhost:5261

GET {{IgniteDistribCaching_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{IgniteDistribCaching_HostAddress}}/weatherforecast_hybrid/
Accept: application/json

###
